name: Build document

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true
      - name: Checkout discorb
        uses: actions/checkout@v2
        with:
          repository: "discorb-lib/discorb"
          path: "discorb"
          fetch-depth: 0
      - name: Checkout discorb-doc
        uses: actions/checkout@v2
        with:
          repository: "discorb-lib/discorb-doc"
          path: "discorb-doc"
      - name: Install dependencies
        run: |
          cd discorb
          gem update uri
          bundle config --local with 'docs'
          bundle install
          cd ../discorb-doc
          npm install
      - name: Generate db
        run: |
          cd discorb-doc
          ruby scripts/namespaces.rb
          ruby scripts/methods.rb
          ruby scripts/files.rb
      - name: Generate with Next.js
        run: |
          cd discorb-doc
          rake build_all
        env:
          URL_PREFIX: "discorb-doc"
      - name: Change for GitHub Pages
        run: |
          cd discorb-doc
          ls | grep -v -E '^(.git|out)$' | xargs rm -rf
          mv out/* .
          touch .nojekyll
      - name: Push document
        run: |
          cd discorb-doc
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git switch -c gh-pages
          git add .
          git add _next -f
          git commit -m "Update: Update document"
          git push origin gh-pages -f
