name: Build YARD with main

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true
      - name: Checkout discorb
        uses: actions/checkout@v2
        with:
          repository: "discorb-lib/discorb"
          path: "discorb"
      - name: Checkout discorb-doc
        uses: actions/checkout@v2
        with:
          repository: "discorb-lib/discorb-doc"
          path: "discorb-doc"
      - name: Install dependencies
        run: |
          cd discorb
          gem update uri
          bundle config --local with 'docs'
          bundle install
          cd ../discorb-doc
          npm install
      - name: Generate document
        run: |
          cd discorb
          bundle exec rake document
      - name: Generate db
        run: |
          cd discorb-doc
          ruby scripts/namespace.rb
          ruby scripts/getter.rb
          ruby scripts/files.rb
      - name: Generate with Next.js
        run: |
          cd discorb-doc
          touch public/.nojekyll
          npm run build
          npx next export
        env:
          URL_PREFIX: "discorb-doc"
      - name: Change for GitHub Pages
        run: |
          cd discorb-doc
          ls | grep -v -E '^(.git|out)$' | xargs rm -rf
          mv out/* .
      - name: Push document
        run: |
          cd discorb-doc
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git switch -c gh-pages
          git add .
          git commit -m "Update: Update document"
          git push origin gh-pages -f
